# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67e1841437de80228e9f0f4636135dadb556a4ccc485afe74eb4c24daaa80bfa2c4fe22a424f392c6188df5f8ebe4dee3d43b8ac050c2163057547dc9e563b86

test:
  secret_key_base: b5dd31dad75202a3a4641e6bcc17ad78f363a1e5092021c0a7503d4aa360f44ac08d4f2817aa9a0ef32b3501fb6771c56abbf3208a2bdc5bc794991b7313af7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
